### ISSUE TITLE
Question about Figure 4 in the paper

### ISSUE THREAD

**Issue by krumo** [theo2021/OnDA#2]
Hi, thanks for your great work! I have a question about Figure 4 in the paper. 

If I understand it correctly, the dashed line is the performance of models in the bold line on different domains. In that case, in Figure 4(b) there are 2 yellow bold segments, does it mean that there should be two models and 2 two yellow dashed lines on 25mm for evaluating on all domains?

What's more, now that the mIoU of yellow dashed line is basically above red, purple, brown lines, does it mean that the model adapted to 25mm could perform better than your online adapted models? If that's true, why do we still need to perform online adaptation for other conditions?

I think there must be something wrong for my understanding about your figure. Could you explain more about it so that I don't misunderstand it? Thanks in advance!

**Comment by theo2021** [comment]
Hi, we had similar questions about this figure. I think it is hard to understand it because there aren't any other similar benchmarks. The figure shows actually one model. 
![image](https://user-images.githubusercontent.com/25212587/201667385-62809505-048d-459c-8fb7-e347012e2ad0.png)
We want to simulate an increasing storm, thus we use rain with increasing intensities: 25,50,75,100, and 200. As you can see at the top of the plot. After we finish an epoch we record the validation accuracies in **every** domain (dashed lines). We then use the bold lines to show in which domain we currently are.

Again 1 model goes through domains 25,50,75,100,200,100,75,50,25,clear. The model adapts always on the current domain on the 25mm domain the model is adapting to 25mm. We are curious to learn how good much better the model becomes in other domains as well.
